services:
  db:
    image: kartoza/postgis:16-3.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: smul
      POSTGRES_USER: dc3
      POSTGRES_PASSWORD: dc3dc3
    ports:
      - '5432:5432'
